// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZsdoryqXYK_QEA2BrJmdoJAgxuQF7l08',
    appId: '1:1023823563078:web:82f4b4654d482e0ede3d47',
    messagingSenderId: '1023823563078',
    projectId: 'test-flutter-apps-d49c7',
    authDomain: 'test-flutter-apps-d49c7.firebaseapp.com',
    storageBucket: 'test-flutter-apps-d49c7.appspot.com',
    measurementId: 'G-YJHVXXYEVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVkTQ5EX05ygz8UEsZy9BnOij6IdGR1ZA',
    appId: '1:1023823563078:android:1e9a5803704eab20de3d47',
    messagingSenderId: '1023823563078',
    projectId: 'test-flutter-apps-d49c7',
    storageBucket: 'test-flutter-apps-d49c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcdw1gyBzWobokku0z6c5eVqyxo__UEqU',
    appId: '1:1023823563078:ios:1ff02ba631b1078ede3d47',
    messagingSenderId: '1023823563078',
    projectId: 'test-flutter-apps-d49c7',
    storageBucket: 'test-flutter-apps-d49c7.appspot.com',
    iosBundleId: 'co.com.daval.authFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcdw1gyBzWobokku0z6c5eVqyxo__UEqU',
    appId: '1:1023823563078:ios:1ff02ba631b1078ede3d47',
    messagingSenderId: '1023823563078',
    projectId: 'test-flutter-apps-d49c7',
    storageBucket: 'test-flutter-apps-d49c7.appspot.com',
    iosBundleId: 'co.com.daval.authFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZsdoryqXYK_QEA2BrJmdoJAgxuQF7l08',
    appId: '1:1023823563078:web:e06c4a44bb4e5ae6de3d47',
    messagingSenderId: '1023823563078',
    projectId: 'test-flutter-apps-d49c7',
    authDomain: 'test-flutter-apps-d49c7.firebaseapp.com',
    storageBucket: 'test-flutter-apps-d49c7.appspot.com',
    measurementId: 'G-NCQ2KELX3F',
  );
}
